server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication_ms
    username: postgress
    password: 123456
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

bezkoder:
  app:
    jwtSecret: ajudaqui-ms
    jwtExpirationMs: 86400000

