spring:
  datasource:
    url: jdbc:postgresql://172.22.0.2:5432/bill_manager
    username: postgress
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update

# logging.level.org.springframework: DEBUG
# spring.devtools.restart.enabled: false

url:
  authenticador: http://localhost:8082

