version: '3'
services:
  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SPRING_APPLICATION_NAME=discovery-server-api
      - SERVER_PORT=8761
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
    networks:
      - eureka-network

networks:
  eureka-network:
    driver: bridge

